Fix #39 by porting colonel to 1.19
PaperMC/adventure-platform-mod pull request #40
Opened 2022-06-17 07:45 UTC by jpenilla

2022-06-17 20:02 UTC, Kas-tle commented
This resolves the problem for me. Thank you for all your hard work :)

2022-06-18 08:15 UTC, HugPhiluu commented
Resolves the problem for me as well! Thank you very much <3

2022-06-18 17:19 UTC, zml2008 requested changes

2022-06-18 17:19 UTC, zml2008 commented on src/main/java/net/kyori/adventure/platform/fabric/impl/ServerboundRegisteredArgumentTypesPacket.java
> +  public static final ResourceLocation ID = new ResourceLocation(Adventure.NAMESPACE, "registered-args");
```suggestion
  public static final ResourceLocation ID = new ResourceLocation(Adventure.NAMESPACE, "registered_args");
```

2022-06-18 17:24 UTC, zml2008 requested changes

2022-06-18 17:24 UTC, zml2008 commented on src/main/java/net/kyori/adventure/platform/fabric/impl/ClientboundArgumentTypeMappingsPacket.java
> +  public static final ResourceLocation ID = new ResourceLocation(Adventure.NAMESPACE, "registered-arg-mappings");
```suggestion
  public static final ResourceLocation ID = new ResourceLocation(Adventure.NAMESPACE, "registered_arg_mappings");
```

2022-06-18 18:20 UTC, zml2008 approved these changes

2022-06-18 18:20 UTC, merged